# Generated by Django 4.2.25 on 2026-02-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_user_avatar_alter_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
